stages:
  - test
  - compile
  - dockerize

test-job1:
  image:
    name: alpine:3.17
    pull_policy: if-not-present
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  image:
    name: alpine:3.17
    pull_policy: if-not-present
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  image:
    name: alpine:3.17
    pull_policy: if-not-present
  stage: compile
  script:
    - echo "This job compiles something from the $CI_COMMIT_BRANCH branch"
