// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: internal/proto/fancam/fancam.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_MALE   Gender = 0
	Gender_FEMALE Gender = 1
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
	}
	Gender_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_fancam_fancam_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_internal_proto_fancam_fancam_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_fancam_fancam_proto_rawDescGZIP(), []int{0}
}

type FancamList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fancams []*FancamObject `protobuf:"bytes,1,rep,name=fancams,proto3" json:"fancams,omitempty"`
}

func (x *FancamList) Reset() {
	*x = FancamList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_fancam_fancam_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FancamList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FancamList) ProtoMessage() {}

func (x *FancamList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fancam_fancam_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FancamList.ProtoReflect.Descriptor instead.
func (*FancamList) Descriptor() ([]byte, []int) {
	return file_internal_proto_fancam_fancam_proto_rawDescGZIP(), []int{0}
}

func (x *FancamList) GetFancams() []*FancamObject {
	if x != nil {
		return x.Fancams
	}
	return nil
}

type FancamObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	YtLink        string                 `protobuf:"bytes,3,opt,name=yt_link,json=ytLink,proto3" json:"yt_link,omitempty"`
	RecordDate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=record_date,json=recordDate,proto3" json:"record_date,omitempty"`
	Artists       []*ArtistObject        `protobuf:"bytes,5,rep,name=artists,proto3" json:"artists,omitempty"`
	SuggestedTags []*SuggestedTags       `protobuf:"bytes,6,rep,name=suggested_tags,json=suggestedTags,proto3" json:"suggested_tags,omitempty"`
}

func (x *FancamObject) Reset() {
	*x = FancamObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_fancam_fancam_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FancamObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FancamObject) ProtoMessage() {}

func (x *FancamObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fancam_fancam_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FancamObject.ProtoReflect.Descriptor instead.
func (*FancamObject) Descriptor() ([]byte, []int) {
	return file_internal_proto_fancam_fancam_proto_rawDescGZIP(), []int{1}
}

func (x *FancamObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FancamObject) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FancamObject) GetYtLink() string {
	if x != nil {
		return x.YtLink
	}
	return ""
}

func (x *FancamObject) GetRecordDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordDate
	}
	return nil
}

func (x *FancamObject) GetArtists() []*ArtistObject {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *FancamObject) GetSuggestedTags() []*SuggestedTags {
	if x != nil {
		return x.SuggestedTags
	}
	return nil
}

type GetFancamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetFancamsRequest) Reset() {
	*x = GetFancamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_fancam_fancam_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFancamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFancamsRequest) ProtoMessage() {}

func (x *GetFancamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fancam_fancam_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFancamsRequest.ProtoReflect.Descriptor instead.
func (*GetFancamsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_fancam_fancam_proto_rawDescGZIP(), []int{2}
}

func (x *GetFancamsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ArtistObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StageName       string                 `protobuf:"bytes,2,opt,name=stage_name,json=stageName,proto3" json:"stage_name,omitempty"`
	FullName        string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	KoreanName      string                 `protobuf:"bytes,4,opt,name=korean_name,json=koreanName,proto3" json:"korean_name,omitempty"`
	KoreanStageName string                 `protobuf:"bytes,5,opt,name=korean_stage_name,json=koreanStageName,proto3" json:"korean_stage_name,omitempty"`
	Dob             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=dob,proto3" json:"dob,omitempty"`
	Group           string                 `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	Country         string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	Height          int32                  `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	Weight          int32                  `protobuf:"varint,10,opt,name=weight,proto3" json:"weight,omitempty"`
	Birthplace      string                 `protobuf:"bytes,11,opt,name=birthplace,proto3" json:"birthplace,omitempty"`
	Gender          Gender                 `protobuf:"varint,12,opt,name=gender,proto3,enum=Gender" json:"gender,omitempty"`
	Instagram       string                 `protobuf:"bytes,13,opt,name=instagram,proto3" json:"instagram,omitempty"`
}

func (x *ArtistObject) Reset() {
	*x = ArtistObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_fancam_fancam_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtistObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistObject) ProtoMessage() {}

func (x *ArtistObject) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fancam_fancam_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistObject.ProtoReflect.Descriptor instead.
func (*ArtistObject) Descriptor() ([]byte, []int) {
	return file_internal_proto_fancam_fancam_proto_rawDescGZIP(), []int{3}
}

func (x *ArtistObject) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtistObject) GetStageName() string {
	if x != nil {
		return x.StageName
	}
	return ""
}

func (x *ArtistObject) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ArtistObject) GetKoreanName() string {
	if x != nil {
		return x.KoreanName
	}
	return ""
}

func (x *ArtistObject) GetKoreanStageName() string {
	if x != nil {
		return x.KoreanStageName
	}
	return ""
}

func (x *ArtistObject) GetDob() *timestamppb.Timestamp {
	if x != nil {
		return x.Dob
	}
	return nil
}

func (x *ArtistObject) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ArtistObject) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ArtistObject) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ArtistObject) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ArtistObject) GetBirthplace() string {
	if x != nil {
		return x.Birthplace
	}
	return ""
}

func (x *ArtistObject) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_MALE
}

func (x *ArtistObject) GetInstagram() string {
	if x != nil {
		return x.Instagram
	}
	return ""
}

type SuggestedTags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnArtist []string `protobuf:"bytes,1,rep,name=en_artist,json=enArtist,proto3" json:"en_artist,omitempty"`
	EnGroup  []string `protobuf:"bytes,2,rep,name=en_group,json=enGroup,proto3" json:"en_group,omitempty"`
	EnSong   []string `protobuf:"bytes,3,rep,name=en_song,json=enSong,proto3" json:"en_song,omitempty"`
	KrArtist []string `protobuf:"bytes,4,rep,name=kr_artist,json=krArtist,proto3" json:"kr_artist,omitempty"`
	KrGroup  []string `protobuf:"bytes,5,rep,name=kr_group,json=krGroup,proto3" json:"kr_group,omitempty"`
	KrSong   []string `protobuf:"bytes,6,rep,name=kr_song,json=krSong,proto3" json:"kr_song,omitempty"`
}

func (x *SuggestedTags) Reset() {
	*x = SuggestedTags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_fancam_fancam_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuggestedTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestedTags) ProtoMessage() {}

func (x *SuggestedTags) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fancam_fancam_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestedTags.ProtoReflect.Descriptor instead.
func (*SuggestedTags) Descriptor() ([]byte, []int) {
	return file_internal_proto_fancam_fancam_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestedTags) GetEnArtist() []string {
	if x != nil {
		return x.EnArtist
	}
	return nil
}

func (x *SuggestedTags) GetEnGroup() []string {
	if x != nil {
		return x.EnGroup
	}
	return nil
}

func (x *SuggestedTags) GetEnSong() []string {
	if x != nil {
		return x.EnSong
	}
	return nil
}

func (x *SuggestedTags) GetKrArtist() []string {
	if x != nil {
		return x.KrArtist
	}
	return nil
}

func (x *SuggestedTags) GetKrGroup() []string {
	if x != nil {
		return x.KrGroup
	}
	return nil
}

func (x *SuggestedTags) GetKrSong() []string {
	if x != nil {
		return x.KrSong
	}
	return nil
}

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_fancam_fancam_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_fancam_fancam_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_internal_proto_fancam_fancam_proto_rawDescGZIP(), []int{5}
}

func (x *ID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_internal_proto_fancam_fancam_proto protoreflect.FileDescriptor

var file_internal_proto_fancam_fancam_proto_rawDesc = []byte{
	0x0a, 0x22, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x66, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x2f, 0x66, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x35, 0x0a, 0x0a, 0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x27, 0x0a, 0x07, 0x66, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x07, 0x66, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x73, 0x22, 0xea, 0x01, 0x0a, 0x0c, 0x46, 0x61,
	0x6e, 0x63, 0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x79, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x79, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x12,
	0x35, 0x0a, 0x0e, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x67,
	0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x54, 0x61, 0x67, 0x73, 0x52, 0x0d, 0x73, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x54, 0x61, 0x67, 0x73, 0x22, 0x25, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6e,
	0x63, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x94, 0x03,
	0x0a, 0x0c, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6b, 0x6f,
	0x72, 0x65, 0x61, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6b, 0x6f, 0x72, 0x65, 0x61, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x6b,
	0x6f, 0x72, 0x65, 0x61, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6b, 0x6f, 0x72, 0x65, 0x61, 0x6e, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x64, 0x6f, 0x62, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x03, 0x64, 0x6f, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x69, 0x72, 0x74, 0x68, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x69, 0x72, 0x74, 0x68,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x67,
	0x72, 0x61, 0x6d, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x67, 0x72, 0x61, 0x6d, 0x22, 0xb1, 0x01, 0x0a, 0x0d, 0x53, 0x75, 0x67, 0x67, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x54, 0x61, 0x67, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x5f, 0x61, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x41, 0x72, 0x74,
	0x69, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x17,
	0x0a, 0x07, 0x65, 0x6e, 0x5f, 0x73, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x65, 0x6e, 0x53, 0x6f, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x72, 0x5f, 0x61, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x72, 0x41, 0x72,
	0x74, 0x69, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x72, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x17, 0x0a, 0x07, 0x6b, 0x72, 0x5f, 0x73, 0x6f, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x6b, 0x72, 0x53, 0x6f, 0x6e, 0x67, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x1e,
	0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x32, 0xc7,
	0x01, 0x0a, 0x06, 0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x12, 0x25, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x42, 0x79, 0x49, 0x44, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a,
	0x0d, 0x2e, 0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x00,
	0x12, 0x2f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x73, 0x12, 0x12,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x00, 0x12, 0x36, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x6e, 0x63, 0x61,
	0x6d, 0x73, 0x12, 0x0b, 0x2e, 0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x46, 0x61, 0x6e, 0x63, 0x61, 0x6d, 0x12, 0x03, 0x2e, 0x49, 0x44, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x6a, 0x69, 0x6b, 0x6b,
	0x61, 0x65, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_fancam_fancam_proto_rawDescOnce sync.Once
	file_internal_proto_fancam_fancam_proto_rawDescData = file_internal_proto_fancam_fancam_proto_rawDesc
)

func file_internal_proto_fancam_fancam_proto_rawDescGZIP() []byte {
	file_internal_proto_fancam_fancam_proto_rawDescOnce.Do(func() {
		file_internal_proto_fancam_fancam_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_fancam_fancam_proto_rawDescData)
	})
	return file_internal_proto_fancam_fancam_proto_rawDescData
}

var file_internal_proto_fancam_fancam_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_fancam_fancam_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_fancam_fancam_proto_goTypes = []interface{}{
	(Gender)(0),                   // 0: Gender
	(*FancamList)(nil),            // 1: FancamList
	(*FancamObject)(nil),          // 2: FancamObject
	(*GetFancamsRequest)(nil),     // 3: GetFancamsRequest
	(*ArtistObject)(nil),          // 4: ArtistObject
	(*SuggestedTags)(nil),         // 5: SuggestedTags
	(*ID)(nil),                    // 6: ID
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_internal_proto_fancam_fancam_proto_depIdxs = []int32{
	2,  // 0: FancamList.fancams:type_name -> FancamObject
	7,  // 1: FancamObject.record_date:type_name -> google.protobuf.Timestamp
	4,  // 2: FancamObject.artists:type_name -> ArtistObject
	5,  // 3: FancamObject.suggested_tags:type_name -> SuggestedTags
	7,  // 4: ArtistObject.dob:type_name -> google.protobuf.Timestamp
	0,  // 5: ArtistObject.gender:type_name -> Gender
	6,  // 6: Fancam.GetFancamByID:input_type -> ID
	3,  // 7: Fancam.GetFancams:input_type -> GetFancamsRequest
	1,  // 8: Fancam.CreateFancams:input_type -> FancamList
	6,  // 9: Fancam.DeleteFancam:input_type -> ID
	2,  // 10: Fancam.GetFancamByID:output_type -> FancamObject
	1,  // 11: Fancam.GetFancams:output_type -> FancamList
	8,  // 12: Fancam.CreateFancams:output_type -> google.protobuf.Empty
	8,  // 13: Fancam.DeleteFancam:output_type -> google.protobuf.Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_proto_fancam_fancam_proto_init() }
func file_internal_proto_fancam_fancam_proto_init() {
	if File_internal_proto_fancam_fancam_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_fancam_fancam_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FancamList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_fancam_fancam_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FancamObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_fancam_fancam_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFancamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_fancam_fancam_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtistObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_fancam_fancam_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuggestedTags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_fancam_fancam_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_fancam_fancam_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_fancam_fancam_proto_goTypes,
		DependencyIndexes: file_internal_proto_fancam_fancam_proto_depIdxs,
		EnumInfos:         file_internal_proto_fancam_fancam_proto_enumTypes,
		MessageInfos:      file_internal_proto_fancam_fancam_proto_msgTypes,
	}.Build()
	File_internal_proto_fancam_fancam_proto = out.File
	file_internal_proto_fancam_fancam_proto_rawDesc = nil
	file_internal_proto_fancam_fancam_proto_goTypes = nil
	file_internal_proto_fancam_fancam_proto_depIdxs = nil
}
